sudo: required
dist: trusty
language: node_js
node_js:
  - "8.9.4"

branches:
  only:
    - master
    - develop

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - pushd $TRAVIS_BUILD_DIR
  - source scripts/setup.sh || exit 1


script:
  - ng build --prod
  

notifications:
  email:
    on_failure: change
    on_success: change
